di "$S_TIME"
clear
set more off
tempfile pde_2013 pde_2014 pde2013bc pde2014bc 
use usrds_id srvc_dt gnn using "/dcs01/igm/segevlab/data/usrds2015/claims/pd/pde2013",clear
save `pde_2013',replace
use usrds_id srvc_dt gnn using "/dcs01/igm/segevlab/data/usrds2016/claims/pd/pde2014",clear
save `pde_2014',replace
local year "y=2013/2014"
forvalues `year' {
  capture use `pde_`y'',clear
	if _rc==0 {
		di "processing pde_`y'.dta ..."
gen	 antipsy1=(strpos(gnn,"ABAPERIDONE")!=0)
gen	 antipsy2=(strpos(gnn,"ACEPERONE")!=0)
gen	 antipsy3=(strpos(gnn,"ACEPROMAZINE")!=0)
gen	 antipsy4=(strpos(gnn,"ACEPROMETAZINE")!=0)
gen	 antipsy5=(strpos(gnn,"ACETOPHENAZINE")!=0)
gen	 antipsy6=(strpos(gnn,"ADOPRAZINE")!=0)
gen	 antipsy7=(strpos(gnn,"ALENTAMOL")!=0)
gen	 antipsy8=(strpos(gnn,"ALIMEMAZINE")!=0)
gen	 antipsy9=(strpos(gnn,"AMISULPRIDE")!=0)
gen	 antipsy10=(strpos(gnn,"AMPEROZIDE")!=0)
gen	 antipsy11=(strpos(gnn,"APLINDORE")!=0)
gen	 antipsy12=(strpos(gnn,"ARIPIPRAZOLE")!=0)
gen	 antipsy13=(strpos(gnn,"ASENAPINE")!=0)
gen	 antipsy14=(strpos(gnn,"AZAPERONE")!=0)
gen	 antipsy15=(strpos(gnn,"BALIPODECT")!=0)
gen	 antipsy16=(strpos(gnn,"BATELAPINE")!=0)
gen	 antipsy17=(strpos(gnn,"BELAPERIDONE")!=0)
gen	 antipsy18=(strpos(gnn,"BENPERIDOL")!=0)
gen	 antipsy19=(strpos(gnn,"BERUPIPAM")!=0)
gen	 antipsy20=(strpos(gnn,"BIFEPRUNOX")!=0)
gen	 antipsy21=(strpos(gnn,"BITOPERTIN")!=0)
gen	 antipsy22=(strpos(gnn,"BLONANSERIN")!=0)
gen	 antipsy23=(strpos(gnn,"BREXPIPRAZOLE")!=0)
gen	 antipsy24=(strpos(gnn,"BROFOXINE")!=0)
gen	 antipsy25=(strpos(gnn,"BROMOSPIPERONE")!=0)
gen	 antipsy26=(strpos(gnn,"BROMPERIDOL")!=0)
gen	 antipsy27=(strpos(gnn,"BUTACLAMOL")!=0)
gen	 antipsy28=(strpos(gnn,"BUTAPERAZINE")!=0)
gen	 antipsy29=(strpos(gnn,"CARFENAZINE")!=0)
gen	 antipsy30=(strpos(gnn,"CARIPRAZINE")!=0)
gen	 antipsy31=(strpos(gnn,"CARPIPRAMINE")!=0)
gen	 antipsy32=(strpos(gnn,"CARVOTROLINE")!=0)
gen	 antipsy33=(strpos(gnn,"CENTBUTINDOLE")!=0)
gen	 antipsy34=(strpos(gnn,"CHLORPHENETHAZINE")!=0)
gen	 antipsy35=(strpos(gnn,"CHLORPROETHAZINE")!=0)
gen	 antipsy36=(strpos(gnn,"CHLORPROMAZINE")!=0)
gen	 antipsy37=(strpos(gnn,"CHLORPROTHIXENE")!=0)
gen	 antipsy38=(strpos(gnn,"CINUPERONE")!=0)
gen	 antipsy39=(strpos(gnn,"CLOCAPRAMINE")!=0)
gen	 antipsy40=(strpos(gnn,"CLOFLUMIDE MESILATE")!=0)
gen	 antipsy41=(strpos(gnn,"CLOFLUPEROL")!=0)
gen	 antipsy42=(strpos(gnn,"CLOPENTHIXOL")!=0)
gen	 antipsy43=(strpos(gnn,"CLOPIMOZIDE")!=0)
gen	 antipsy44=(strpos(gnn,"CLOPIPAZAN")!=0)
gen	 antipsy45=(strpos(gnn,"CLOSPIPRAMINE")!=0)
gen	 antipsy46=(strpos(gnn,"CLOTHIAPINE")!=0)
gen	 antipsy47=(strpos(gnn,"CLOTIAPINE")!=0)
gen	 antipsy48=(strpos(gnn,"CLOZAPINE")!=0)
gen	 antipsy49=(strpos(gnn,"CYAMEMAZINE")!=0)
gen	 antipsy50=(strpos(gnn,"DAPIPRAZOLE")!=0)
gen	 antipsy51=(strpos(gnn,"DEUTETRABENAZINE")!=0)
gen	 antipsy52=(strpos(gnn,"DICARBINE")!=0)
gen	 antipsy53=(strpos(gnn,"DIMETOTIAZINE")!=0)
gen	 antipsy54=(strpos(gnn,"DIXYRAZINE")!=0)
gen	 antipsy55=(strpos(gnn,"DOLASETRON MESILATE")!=0)
gen	 antipsy56=(strpos(gnn,"DROPERIDOL")!=0)
gen	 antipsy57=(strpos(gnn,"DUOPERONE")!=0)
gen	 antipsy58=(strpos(gnn,"ECOPIPAM")!=0)
gen	 antipsy59=(strpos(gnn,"ELOPIPRAZOLE")!=0)
gen	 antipsy60=(strpos(gnn,"EMONAPRIDE")!=0)
gen	 antipsy61=(strpos(gnn,"ETAZOLATE")!=0)
gen	 antipsy62=(strpos(gnn,"ETYMEMAZINE")!=0)
gen	 antipsy63=(strpos(gnn,"EVENAMIDE")!=0)
gen	 antipsy64=(strpos(gnn,"FANANSERIN")!=0)
gen	 antipsy65=(strpos(gnn,"FARAMPATOR")!=0)
gen	 antipsy66=(strpos(gnn,"FENCAMFAMINE")!=0)
gen	 antipsy67=(strpos(gnn,"FLUANISONE")!=0)
gen	 antipsy68=(strpos(gnn,"FLUPENTHIXOL")!=0)
gen	 antipsy69=(strpos(gnn,"FLUPENTIXOL")!=0)
gen	 antipsy70=(strpos(gnn,"FLUPERLAPINE")!=0)
gen	 antipsy71=(strpos(gnn,"FLUPHENAZINE")!=0)
gen	 antipsy72=(strpos(gnn,"FLUSPIRILENE")!=0)
gen	 antipsy73=(strpos(gnn,"FLUTROLINE")!=0)
gen	 antipsy74=(strpos(gnn,"GEVETROLINE")!=0)
gen	 antipsy75=(strpos(gnn,"HALOPERIDOL")!=0)
gen	 antipsy76=(strpos(gnn,"ILOPERIDONE")!=0)
gen	 antipsy77=(strpos(gnn,"ISOFLOXYTHEPIN")!=0)
gen	 antipsy78=(strpos(gnn,"ISOMOLPAN")!=0)
gen	 antipsy79=(strpos(gnn,"LAMOTRIGINE")!=0)
gen	 antipsy80=(strpos(gnn,"LANDIPIRDINE")!=0)
gen	 antipsy81=(strpos(gnn,"LENPERONE")!=0)
gen	 antipsy82=(strpos(gnn,"LEVOMEPROMAZINE")!=0)
gen	 antipsy83=(strpos(gnn,"LOXAPINE")!=0)
gen	 antipsy84=(strpos(gnn,"LUMATEPERONE")!=0)
gen	 antipsy85=(strpos(gnn,"LURASIDONE")!=0)
gen	 antipsy86=(strpos(gnn,"LYSERGOL")!=0)
gen	 antipsy87=(strpos(gnn,"MARDEPODECT")!=0)
gen	 antipsy88=(strpos(gnn,"MAROXEPINE")!=0)
gen	 antipsy89=(strpos(gnn,"MAZAPERTINE")!=0)
gen	 antipsy90=(strpos(gnn,"MELPERONE")!=0)
gen	 antipsy91=(strpos(gnn,"MEPIPRAZOLE")!=0)
gen	 antipsy92=(strpos(gnn,"MESORIDAZINE")!=0)
gen	 antipsy93=(strpos(gnn,"METHIOTHEPIN")!=0)
gen	 antipsy94=(strpos(gnn,"METHOPROMAZINE")!=0)
gen	 antipsy95=(strpos(gnn,"METOFENAZATE")!=0)
gen	 antipsy96=(strpos(gnn,"METYLPERON")!=0)
gen	 antipsy97=(strpos(gnn,"MOLINDONE")!=0)
gen	 antipsy98=(strpos(gnn,"MOPERONE")!=0)
gen	 antipsy99=(strpos(gnn,"NEBOGLAMINE")!=0)
gen	 antipsy100=(strpos(gnn,"NEMONAPRIDE")!=0)
gen	 antipsy101=(strpos(gnn,"NOCTRAN")!=0)
gen	 antipsy102=(strpos(gnn,"NORCHLORPROMAZINE")!=0)
gen	 antipsy103=(strpos(gnn,"NORCLOZAPINE")!=0)
gen	 antipsy104=(strpos(gnn,"OCAPERIDONE")!=0)
gen	 antipsy105=(strpos(gnn,"OLANZAPINE")!=0)
gen	 antipsy106=(strpos(gnn,"ONDANSETRON")!=0)
gen	 antipsy107=(strpos(gnn,"OXIPEROMIDE")!=0)
gen	 antipsy108=(strpos(gnn,"OXYPERTINE")!=0)
gen	 antipsy109=(strpos(gnn,"OXYPROTHEPINE")!=0)
gen	 antipsy110=(strpos(gnn,"PALIPERIDONE")!=0)
gen	 antipsy111=(strpos(gnn,"PANAMESINE")!=0)
gen	 antipsy112=(strpos(gnn,"PECAZINE")!=0)
gen	 antipsy113=(strpos(gnn,"PENFLURIDOL")!=0)
gen	 antipsy114=(strpos(gnn,"PENTIAPINE")!=0)
gen	 antipsy115=(strpos(gnn,"PERAZINE")!=0)
gen	 antipsy116=(strpos(gnn,"PERICIAZINE")!=0)
gen	 antipsy117=(strpos(gnn,"PERIMETAZINE")!=0)
gen	 antipsy118=(strpos(gnn,"PERLAPINE")!=0)
gen	 antipsy119=(strpos(gnn,"PEROSPIRONE")!=0)
gen	 antipsy120=(strpos(gnn,"PERPHENAZINE")!=0)
gen	 antipsy121=(strpos(gnn,"PICOBENZIDE")!=0)
gen	 antipsy122=(strpos(gnn,"PIFLUTIXOL")!=0)
gen	 antipsy123=(strpos(gnn,"PIMAVANSERIN")!=0)
gen	 antipsy124=(strpos(gnn,"PIMETHIXENE")!=0)
gen	 antipsy125=(strpos(gnn,"PIMOZIDE")!=0)
gen	 antipsy126=(strpos(gnn,"PIPAMPERONE")!=0)
gen	 antipsy127=(strpos(gnn,"PIPERACETAZINE")!=0)
gen	 antipsy128=(strpos(gnn,"PIPOTIAZINE")!=0)
gen	 antipsy129=(strpos(gnn,"PIRENPERONE")!=0)
gen	 antipsy130=(strpos(gnn,"POMAGLUMETAD METHIONIL")!=0)
gen	 antipsy131=(strpos(gnn,"PRIDOPIDINE")!=0)
gen	 antipsy132=(strpos(gnn,"PROCHLORPERAZINE")!=0)
gen	 antipsy133=(strpos(gnn,"PROFENAMINE")!=0)
gen	 antipsy134=(strpos(gnn,"PROMAZINE")!=0)
gen	 antipsy135=(strpos(gnn,"PROPIOMAZINE")!=0)
gen	 antipsy136=(strpos(gnn,"PROPIONYLPROMAZINE")!=0)
gen	 antipsy137=(strpos(gnn,"PROTHIPENDYL")!=0)
gen	 antipsy138=(strpos(gnn,"QUETIAPINE")!=0)
gen	 antipsy139=(strpos(gnn,"RACLOPRIDE")!=0)
gen	 antipsy140=(strpos(gnn,"REMOXIPRIDE")!=0)
gen	 antipsy141=(strpos(gnn,"RESERPINE")!=0)
gen	 antipsy142=(strpos(gnn,"RILAPINE")!=0)
gen	 antipsy143=(strpos(gnn,"RIMCAZOLE")!=0)
gen	 antipsy144=(strpos(gnn,"RISPERIDONE")!=0)
gen	 antipsy145=(strpos(gnn,"RITANSERIN")!=0)
gen	 antipsy146=(strpos(gnn,"ROLUPERIDONE")!=0)
gen	 antipsy147=(strpos(gnn,"ROMERGOLINE")!=0)
gen	 antipsy148=(strpos(gnn,"SAVOXEPINE")!=0)
gen	 antipsy149=(strpos(gnn,"SERIDOPIDINE")!=0)
gen	 antipsy150=(strpos(gnn,"SERTINDOLE")!=0)
gen	 antipsy151=(strpos(gnn,"SETOPERONE")!=0)
gen	 antipsy152=(strpos(gnn,"SPIPERONE")!=0)
gen	 antipsy153=(strpos(gnn,"STEPHOLIDINE")!=0)
gen	 antipsy154=(strpos(gnn,"SULFORIDAZINE")!=0)
gen	 antipsy155=(strpos(gnn,"SULPIRIDE")!=0)
gen	 antipsy156=(strpos(gnn,"SULTOPRIDE")!=0)
gen	 antipsy157=(strpos(gnn,"TEFLUDAZINE")!=0)
gen	 antipsy158=(strpos(gnn,"TENILAPINE")!=0)
gen	 antipsy159=(strpos(gnn,"TEPIRINDOLE")!=0)
gen	 antipsy160=(strpos(gnn,"TETRABENAZINE")!=0)
gen	 antipsy161=(strpos(gnn,"TETRAHYDROPALMATINE")!=0)
gen	 antipsy162=(strpos(gnn,"THIOPROPAZATE")!=0)
gen	 antipsy163=(strpos(gnn,"THIOPROPERAZINE")!=0)
gen	 antipsy164=(strpos(gnn,"THIORIDAZINE")!=0)
gen	 antipsy165=(strpos(gnn,"THIOTHIXENE")!=0)
gen	 antipsy166=(strpos(gnn,"TIAPRIDE")!=0)
gen	 antipsy167=(strpos(gnn,"TILAPERTIN")!=0)
gen	 antipsy168=(strpos(gnn,"TIMIPERONE")!=0)
gen	 antipsy169=(strpos(gnn,"TIOSPIRONE")!=0)
gen	 antipsy170=(strpos(gnn,"TIOTIXENE")!=0)
gen	 antipsy171=(strpos(gnn,"TRIETHYLPERAZINE")!=0)
gen	 antipsy172=(strpos(gnn,"TRIFLUOPERAZINE")!=0)
gen	 antipsy173=(strpos(gnn,"TRIFLUPERIDOL")!=0)
gen	 antipsy174=(strpos(gnn,"TRIFLUPROMAZINE")!=0)
gen	 antipsy175=(strpos(gnn,"TULRAMPATOR")!=0)
gen	 antipsy176=(strpos(gnn,"UMESPIRONE")!=0)
gen	 antipsy177=(strpos(gnn,"VABICASERIN")!=0)
gen	 antipsy178=(strpos(gnn,"VERALIPRIDE")!=0)
gen	 antipsy179=(strpos(gnn,"VOLINANSERIN")!=0)
gen	 antipsy180=(strpos(gnn,"ZETIDOLINE")!=0)
gen	 antipsy181=(strpos(gnn,"ZICRONAPINE")!=0)
gen	 antipsy182=(strpos(gnn,"ZIPRASIDONE")!=0)
gen	 antipsy183=(strpos(gnn,"ZOLOPERONE")!=0)
gen	 antipsy184=(strpos(gnn,"ZOTEPINE")!=0)
gen	 antipsy185=(strpos(gnn,"ZUCLOPENTHIXOL")!=0)     
		gen  antipsy_rx=( ///	
antipsy1+	///
antipsy2+	///
antipsy3+	///
antipsy4+	///
antipsy5+	///
antipsy6+	///
antipsy7+	///
antipsy8+	///
antipsy9+	///
antipsy10+	///
antipsy11+	///
antipsy12+	///
antipsy13+	///
antipsy14+	///
antipsy15+	///
antipsy16+	///
antipsy17+	///
antipsy18+	///
antipsy19+	///
antipsy20+	///
antipsy21+	///
antipsy22+	///
antipsy23+	///
antipsy24+	///
antipsy25+	///
antipsy26+	///
antipsy27+	///
antipsy28+	///
antipsy29+	///
antipsy30+	///
antipsy31+	///
antipsy32+	///
antipsy33+	///
antipsy34+	///
antipsy35+	///
antipsy36+	///
antipsy37+	///
antipsy38+	///
antipsy39+	///
antipsy40+	///
antipsy41+	///
antipsy42+	///
antipsy43+	///
antipsy44+	///
antipsy45+	///
antipsy46+	///
antipsy47+	///
antipsy48+	///
antipsy49+	///
antipsy50+	///
antipsy51+	///
antipsy52+	///
antipsy53+	///
antipsy54+	///
antipsy55+	///
antipsy56+	///
antipsy57+	///
antipsy58+	///
antipsy59+	///
antipsy60+	///
antipsy61+	///
antipsy62+	///
antipsy63+	///
antipsy64+	///
antipsy65+	///
antipsy66+	///
antipsy67+	///
antipsy68+	///
antipsy69+	///
antipsy70+	///
antipsy71+	///
antipsy72+	///
antipsy73+	///
antipsy74+	///
antipsy75+	///
antipsy76+	///
antipsy77+	///
antipsy78+	///
antipsy79+	///
antipsy80+	///
antipsy81+	///
antipsy82+	///
antipsy83+	///
antipsy84+	///
antipsy85+	///
antipsy86+	///
antipsy87+	///
antipsy88+	///
antipsy89+	///
antipsy90+	///
antipsy91+	///
antipsy92+	///
antipsy93+	///
antipsy94+	///
antipsy95+	///
antipsy96+	///
antipsy97+	///
antipsy98+	///
antipsy99+	///
antipsy100+	///
antipsy101+	///
antipsy102+	///
antipsy103+	///
antipsy104+	///
antipsy105+	///
antipsy106+	///
antipsy107+	///
antipsy108+	///
antipsy109+	///
antipsy110+	///
antipsy111+	///
antipsy112+	///
antipsy113+	///
antipsy114+	///
antipsy115+	///
antipsy116+	///
antipsy117+	///
antipsy118+	///
antipsy119+	///
antipsy120+	///
antipsy121+	///
antipsy122+	///
antipsy123+	///
antipsy124+	///
antipsy125+	///
antipsy126+	///
antipsy127+	///
antipsy128+	///
antipsy129+	///
antipsy130+	///
antipsy131+	///
antipsy132+	///
antipsy133+	///
antipsy134+	///
antipsy135+	///
antipsy136+	///
antipsy137+	///
antipsy138+	///
antipsy139+	///
antipsy140+	///
antipsy141+	///
antipsy142+	///
antipsy143+	///
antipsy144+	///
antipsy145+	///
antipsy146+	///
antipsy147+	///
antipsy148+	///
antipsy149+	///
antipsy150+	///
antipsy151+	///
antipsy152+	///
antipsy153+	///
antipsy154+	///
antipsy155+	///
antipsy156+	///
antipsy157+	///
antipsy158+	///
antipsy159+	///
antipsy160+	///
antipsy161+	///
antipsy162+	///
antipsy163+	///
antipsy164+	///
antipsy165+	///
antipsy166+	///
antipsy167+	///
antipsy168+	///
antipsy169+	///
antipsy170+	///
antipsy171+	///
antipsy172+	///
antipsy173+	///
antipsy174+	///
antipsy175+	///
antipsy176+	///
antipsy177+	///
antipsy178+	///
antipsy179+	///
antipsy180+	///
antipsy181+	///
antipsy182+	///
antipsy183+	///
antipsy184+	///
antipsy185	///
>0)
keep usrds_id srvc_dt antipsy_rx 
duplicates drop
quietly compress
save `pde`y'bc', replace
	}
}

forvalues `year' {
		 capture append using `pde`y'bc'
}
save 10_antipsychotics_expR.dta,replace
di "$S_TIME"
